### ISSUE TITLE
'drush make ...' command typo error ?

### ISSUE THREAD

**Issue by fenix011** [GuGuss/drupal-starter-profile#1]
```
$ drush make make yourprofile/drupal-core.make www
```

should'nt be 

```
$ drush make  yourprofile/project-core.make www
```

?

Thanks for the inspiration

**Comment by GuGuss** [comment]
Hi @jordila,

Thanks for noticing, I just fixed the command ^^

This all workflow for installation profile or using make file is natively supported by [Platform.sh](https://platform.sh). 

I'm sure you might enjoy trying it out for developing your projects ;-)

**Comment by fenix011** [comment]
@GuGuss i'm learning a lot with platform.sh approach ... Thanks.
Mmmh...I cannot easily find it in your webpage, which is the software license ?
I know you are not Openshift, but still ... I'm pretty sure that you'll have more platform.sh users as long as you release it ;-)
